/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessoesRouteRouteImport } from './routes/sessoes.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessoesIndexRouteImport } from './routes/sessoes.index'
import { Route as SessoesIdRouteImport } from './routes/sessoes.$id'
import { Route as SessoesIdExecutarRouteImport } from './routes/sessoes.$id.executar'
import { Route as AuthSpotifyCallbackRouteImport } from './routes/auth.spotify.callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRouteRoute = SessoesRouteRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesIndexRoute = SessoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessoesRouteRoute,
} as any)
const SessoesIdRoute = SessoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessoesRouteRoute,
} as any)
const SessoesIdExecutarRoute = SessoesIdExecutarRouteImport.update({
  id: '/executar',
  path: '/executar',
  getParentRoute: () => SessoesIdRoute,
} as any)
const AuthSpotifyCallbackRoute = AuthSpotifyCallbackRouteImport.update({
  id: '/auth/spotify/callback',
  path: '/auth/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessoes': typeof SessoesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRouteWithChildren
  '/sessoes/': typeof SessoesIndexRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/sessoes/$id/executar': typeof SessoesIdExecutarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRouteWithChildren
  '/sessoes': typeof SessoesIndexRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/sessoes/$id/executar': typeof SessoesIdExecutarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessoes': typeof SessoesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRouteWithChildren
  '/sessoes/': typeof SessoesIndexRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/sessoes/$id/executar': typeof SessoesIdExecutarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessoes'
    | '/login'
    | '/sessoes/$id'
    | '/sessoes/'
    | '/auth/spotify/callback'
    | '/sessoes/$id/executar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sessoes/$id'
    | '/sessoes'
    | '/auth/spotify/callback'
    | '/sessoes/$id/executar'
  id:
    | '__root__'
    | '/'
    | '/sessoes'
    | '/login'
    | '/sessoes/$id'
    | '/sessoes/'
    | '/auth/spotify/callback'
    | '/sessoes/$id/executar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessoesRouteRoute: typeof SessoesRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthSpotifyCallbackRoute: typeof AuthSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/': {
      id: '/sessoes/'
      path: '/'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof SessoesIndexRouteImport
      parentRoute: typeof SessoesRouteRoute
    }
    '/sessoes/$id': {
      id: '/sessoes/$id'
      path: '/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof SessoesIdRouteImport
      parentRoute: typeof SessoesRouteRoute
    }
    '/sessoes/$id/executar': {
      id: '/sessoes/$id/executar'
      path: '/executar'
      fullPath: '/sessoes/$id/executar'
      preLoaderRoute: typeof SessoesIdExecutarRouteImport
      parentRoute: typeof SessoesIdRoute
    }
    '/auth/spotify/callback': {
      id: '/auth/spotify/callback'
      path: '/auth/spotify/callback'
      fullPath: '/auth/spotify/callback'
      preLoaderRoute: typeof AuthSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessoesIdRouteChildren {
  SessoesIdExecutarRoute: typeof SessoesIdExecutarRoute
}

const SessoesIdRouteChildren: SessoesIdRouteChildren = {
  SessoesIdExecutarRoute: SessoesIdExecutarRoute,
}

const SessoesIdRouteWithChildren = SessoesIdRoute._addFileChildren(
  SessoesIdRouteChildren,
)

interface SessoesRouteRouteChildren {
  SessoesIdRoute: typeof SessoesIdRouteWithChildren
  SessoesIndexRoute: typeof SessoesIndexRoute
}

const SessoesRouteRouteChildren: SessoesRouteRouteChildren = {
  SessoesIdRoute: SessoesIdRouteWithChildren,
  SessoesIndexRoute: SessoesIndexRoute,
}

const SessoesRouteRouteWithChildren = SessoesRouteRoute._addFileChildren(
  SessoesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessoesRouteRoute: SessoesRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthSpotifyCallbackRoute: AuthSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
