/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessoesRouteRouteImport } from './routes/sessoes.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessoesIndexRouteImport } from './routes/sessoes.index'
import { Route as SessoesIdRouteImport } from './routes/sessoes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRouteRoute = SessoesRouteRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesIndexRoute = SessoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessoesRouteRoute,
} as any)
const SessoesIdRoute = SessoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessoesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessoes': typeof SessoesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes': typeof SessoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessoes': typeof SessoesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sessoes' | '/login' | '/sessoes/$id' | '/sessoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sessoes/$id' | '/sessoes'
  id: '__root__' | '/' | '/sessoes' | '/login' | '/sessoes/$id' | '/sessoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessoesRouteRoute: typeof SessoesRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/': {
      id: '/sessoes/'
      path: '/'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof SessoesIndexRouteImport
      parentRoute: typeof SessoesRouteRoute
    }
    '/sessoes/$id': {
      id: '/sessoes/$id'
      path: '/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof SessoesIdRouteImport
      parentRoute: typeof SessoesRouteRoute
    }
  }
}

interface SessoesRouteRouteChildren {
  SessoesIdRoute: typeof SessoesIdRoute
  SessoesIndexRoute: typeof SessoesIndexRoute
}

const SessoesRouteRouteChildren: SessoesRouteRouteChildren = {
  SessoesIdRoute: SessoesIdRoute,
  SessoesIndexRoute: SessoesIndexRoute,
}

const SessoesRouteRouteWithChildren = SessoesRouteRoute._addFileChildren(
  SessoesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessoesRouteRoute: SessoesRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
